version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: spacebase_redis
    ports:
      - "6379:6379"

  hazelcast:
    image: hazelcast/hazelcast:5.3
    container_name: spacebase_hazelcast
    ports:
      - "5701:5701"

  product-pu:
    build: .
    container_name: product_pu
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - REDIS_HOST=redis
      - HAZELCAST_ADDRESS=hazelcast:5701
    depends_on:
      - redis
      - hazelcast

  cart-pu:
    build: .
    container_name: cart_pu
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - REDIS_HOST=redis
      - HAZELCAST_ADDRESS=hazelcast:5701
    depends_on:
      - redis
      - hazelcast

  order-pu:
    build: .
    container_name: order_pu
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - REDIS_HOST=redis
      - HAZELCAST_ADDRESS=hazelcast:5701
    depends_on:
      - redis
      - hazelcast

  inventory-pu:
    build: .
    container_name: inventory_pu
    ports:
      - "8084:8084"
    environment:
      - PORT=8084
      - REDIS_HOST=redis
      - HAZELCAST_ADDRESS=hazelcast:5701
    depends_on:
      - redis
      - hazelcast

