spring.application.name=spacebase_achitecture

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Server configurations (can be overridden by docker-compose)
server.port=${SERVER_PORT:8080}

# Allow setting multiple instances
spring.lifecycle.timeout-per-shutdown-phase=20s
